[package]
authors = ["Samuel Keiffer <samuelkeiffer@gmail.com>"]
name = "veloren-server-agent"
edition = "2021"
version = "0.1.0"

[features]
use-dyn-lib = ["common-dynlib"]
be-dyn-lib = []

[dependencies]
common = { package = "veloren-common", path = "../../common"}
common-dynlib = { package = "veloren-common-dynlib", path = "../../common/dynlib", optional = true}
rtsim = { package = "veloren-rtsim", path = "../../rtsim" }

specs = { workspace = true, features = ["shred-derive"] }
vek = { workspace = true }
rand = { workspace = true, features = ["small_rng"] }
itertools = { workspace = true }
lazy_static = { workspace = true }
